name: Deploy to EC2 (Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH into EC2 and deploy (PowerShell)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT || 22 }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; `
              Write-Host 'User:' (whoami); `
              Set-Location 'C:\app\Ovecchia'; `
              & 'C:\Program Files\Git\cmd\git.exe' remote -v; `
              & 'C:\Program Files\Git\cmd\git.exe' fetch --all --prune; `
              & 'C:\Program Files\Git\cmd\git.exe' ls-remote origin -h refs/heads/main; `
              & 'C:\Program Files\Git\cmd\git.exe' reset --hard origin/main; `
              & 'C:\app\Ovecchia\.venv\Scripts\pip.exe' install -r 'C:\app\Ovecchia\requirements.txt'; `
              & 'C:\nssm-2.24\win64\nssm.exe' restart OvecchiaWeb; `
              & 'C:\nssm-2.24\win64\nssm.exe' restart OvecchiaBot; `
              Get-Content 'C:\app\Ovecchia\logs\web_stderr.log' -Tail 50; `
              Get-Content 'C:\app\Ovecchia\logs\bot_stderr.log' -Tail 50"
